### ISSUE TITLE
Im Wartungsmodus lässt sich kein Passwort wiederherstellen -> 503 Service Unavailable

### ISSUE THREAD

**Issue by Ainschy** [markocupic/backend-password-recovery-bundle#1]
Hi,

ist die Seite im Wartungsmodus lässt sich die Erweiterung nicht aufrufen. 

Hast du eine Lösung dazu?

**Comment by markocupic** [comment]
Hallo Oliver
Bin gerade etwas busy...
Nein, der Fall ist mir nicht bekannt, habe es aber auch nie darauf getestet.
Möchtest du debuggen? 
Liebe Grüsse Marko
