### ISSUE TITLE
How to add a link to be_login.htm?

### ISSUE THREAD

**Issue by xstable** [markocupic/backend-password-recovery-bundle#3]
Are there additional steps to install this plugin in the login-template?
An install-instruction is heavily missing here.

If no additional steps are needed, then it doesn't work for 4.9 LTS

**Comment by markocupic** [comment]
No, there are no additional steps needed. Simply run Contao Manager, install the plugin and run the database install tool.

**The link occurs, when you've inserted a false password.**

![image](https://user-images.githubusercontent.com/1525166/120460909-d5d74680-c399-11eb-9996-4d0aadcd2a2e.png)

**Comment by xstable** [comment]
@markocupic nice, I'll try this. 
But is there anyway a way to display this "Passwort remember" link even at the first login-form.
Because there might be users, who know, that they have forgot their password. And instead of calling us in this case, they should see the Link "Password vergessen?" and should be able to use it.

**Comment by xstable** [comment]
@markocupic  Ok, it doesn't work.
I see this Button "Passwort wiederherstellen", but if I click on it, I'm only redirected to the login-page with this URL:

`https://xxx.de/contao/login?_hash=363AegVVDOkojzXjVKFz812317TgG95yEh4%2BZQsbo%3D&redirect=https%3A%2F%2Fxxx.de%2Fbackendpasswordrecovery%2Frequirepasswordrecoverylink%3F_locale%3Dde`

**Comment by markocupic** [comment]
You can use the parseTemplateHook to customize the login template 'be_login'.
Or you could store a customized version of 'be_login.html5' in your templates directory.

**Comment by markocupic** [comment]
> @markocupic Ok, it doesn't work.
> I see this Button "Passwort wiederherstellen", but if I click on it, I'm only redirected to the login-page with this URL:
> 
> `https://xxx.de/contao/login?_hash=363AegVVDOkojzXjVKFz812317TgG95yEh4%2BZQsbo%3D&redirect=https%3A%2F%2Fxxx.de%2Fbackendpasswordrecovery%2Frequirepasswordrecoverylink%3F_locale%3Dde`
confused...
I'm using the plugin at https://https://www.sac-pilatus.ch/contao and it works.

**Comment by xstable** [comment]
Ok, I see. 
Do you have a clue, why my contao redirect this link: https://xxx.de/backendpasswordrecovery/requirepasswordrecoverylink?_locale=de

to such a crappy login-link with hash, lolcale and redirect parameters?
(Im not yet much familiar with contao, so every hint is highly appreciated )

**Comment by markocupic** [comment]
Try the update in at least version [1.3.0](https://github.com/markocupic/backend-password-recovery-bundle/tree/1.3.0)

The "password recovery" link is absolute now. Perhaps this will be the clue.

**Comment by xstable** [comment]
Mhh, even If I paste the link I've posted in my last answer (an absolute one), into the browser-adressbar it redirects to this kind of url with parameters. 
So it might at least not depend at your Plugin.. 
But if you have a hint for me, why my contao is redirecting in such way, that would be great!

Even in my .htaccess there isn't change anything, so I wonder why contao do this redirecting to a parameter-like URL:
```
<IfModule mod_headers.c>
    # Allow access from all domains for webfonts (see contao/core-bundle#528)
    <FilesMatch "\.(ttf|ttc|otf|eot|woff2?|font\.css)$">
        Header set Access-Control-Allow-Origin "*"
    </FilesMatch>
</IfModule>

<IfModule mod_rewrite.c>
    RewriteEngine On
 
    # Determine the RewriteBase automatically and set it as environment variable.
    # If you are using Apache aliases to do mass virtual hosting or installed the
    # project in a subdirectory, the base path will be prepended to allow proper
    # resolution of the app.php file and to redirect to the correct URI. It will
    # work in environments without path prefix as well, providing a safe, one-size
    # fits all solution. But as you do not need it in this case, you can comment
    # the following 2 lines to eliminate the overhead.
    RewriteCond %{REQUEST_URI}::$1 ^(/.+)/(.*)::\2$
    RewriteRule ^(.*) - [E=BASE:%1]

    # Sets the HTTP_AUTHORIZATION header removed by Apache
    RewriteCond %{HTTP:Authorization} .
    RewriteRule ^ - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    # Redirect to URI without front controller to prevent duplicate content
    # (with and without `/app.php`). Only do this redirect on the initial
    # rewrite by Apache and not on subsequent cycles. Otherwise we would get an
    # endless redirect loop (request -> rewrite to front controller ->
    # redirect -> request -> ...).
    # So in case you get a "too many redirects" error or you always get redirected
    # to the start page because your Apache does not expose the REDIRECT_STATUS
    # environment variable, you have 2 choices:
    # - disable this feature by commenting the following 2 lines or
    # - use Apache >= 2.3.9 and replace all L flags by END flags and remove the
    #   following RewriteCond (best solution)
    RewriteCond %{ENV:REDIRECT_STATUS} ^$
    RewriteRule ^app\.php(?:/(.*)|$) %{ENV:BASE}/$1 [R=301,L]

    # If the requested filename exists, simply serve it.
    # We only want to let Apache serve files and not directories.
    RewriteCond %{REQUEST_FILENAME} -f
    RewriteRule ^ - [L]

    # Rewrite all other queries to the front controller.
    RewriteRule ^ %{ENV:BASE}/app.php [L]
</IfModule>

<IfModule !mod_rewrite.c>
    <IfModule mod_alias.c>
        # When mod_rewrite is not available, we instruct a temporary redirect of
        # the start page to the front controller explicitly so that the website
        # and the generated links can still be used.
        RedirectMatch 302 ^/$ /app.php/
        # RedirectTemp cannot be used instead
    </IfModule>
</IfModule>
```

**Comment by markocupic** [comment]
Can you post your composer.json?

**Comment by markocupic** [comment]
Perhaps clearing the browser cache and cookies could be the solution...

**Comment by xstable** [comment]
This is the Composer-file: https://hatebin.com/rqeqjwiqoo

Even in incognito-mode in new Browser that issue happens.

**Comment by markocupic** [comment]
Try to uninstall heimrichhannot/contao-backend-lost-password-bundle--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 02.06.21, 13:09 schrieb Samuel Suther ***@***.***>:

   
  @markocupic nice, I'll try this. But is there anyway a way to display this "Passwort remember" link even at the first login-form. Because there might be users, who know, that they have forgot their password. And instead of calling us in this case, they should see the Link "Password vergessen?" and should be able to use it.

**Comment by xstable** [comment]
**I have new insights:**

1. If I first enter a wrong password, I see the Login-Form with the "Passwort erinnerung" Button.
1. I click it, and come back to the general login-page.
1. BUT if I then insert the real credentials to be logged in, THEN I see your Password-Recovery-Page. 

So the redirect seems to work after I've logged in... that's strange

**Comment by markocupic** [comment]
Can I test this?

**Comment by xstable** [comment]
I've created a video which shows the issue in detail: http://somup.com/cr1nI6q3P2

**Comment by markocupic** [comment]
Do you use a customized be_login.html5 template?

**Comment by xstable** [comment]
Yes, it's this one:  https://0bin.net/paste/zYm1+vXw#ZX3XGUgNPAfOo+UOzrmrYKse67q3dfAS8yWsgoMLZj-

Only changed the style a bit (e.g. the import at line 19).

**Comment by markocupic** [comment]
Have you renamed the template?

**Comment by xstable** [comment]
No: 
![image](https://user-images.githubusercontent.com/1778068/120488618-42147300-c3b7-11eb-80ae-ec844c83ee91.png)

**Comment by xstable** [comment]
I have those atm: 
![image](https://user-images.githubusercontent.com/1778068/120488961-86a00e80-c3b7-11eb-8d6d-e8d56d654fc7.png)

**Comment by markocupic** [comment]
You have enabled two factor authentication?

**Comment by xstable** [comment]
Generally not for sysadmin.
But don't know if it's important or not, the frontend is in /websites and the backend in /contao/web.

I've also login.obkarriere.de on this IONOS-Hosting... interesting fact, that it also redirect with this parameter-stuff

**Comment by markocupic** [comment]
Which contao version are you running 4.9.13?

**Comment by xstable** [comment]
Yes, 4.9.13

**Comment by markocupic** [comment]
If you're logged in (backend)? How's the url is looking then? Is there also a _hash param in there?

**Comment by xstable** [comment]
No, looks like this: https://contao.obkarriere.de/contao?do=themes&ref=qQARU-Jf

**Comment by markocupic** [comment]
The contao demo version 4.9.14 is looking ok also.

https://demo.contao.org/contao

**Comment by markocupic** [comment]
Did you already uninstall the heimrichhannot plugin?

**Comment by xstable** [comment]
Yes, I've still removed it. Issue stay as it was.

I've added this to my htaccess, only to see what happens:
`RewriteRule backendpasswordrecovery/.* - [L]`

And this works... means the URL stay's as it is in the adressbar of the browser... even if there is an error-page, because of the handling by contao is missing to do the internal routing.

So in my opinion, it's something inside of contao itself, right?

**Comment by markocupic** [comment]
Habe mich schlau gemacht. Die Url wird von contao signiert (uri signing), deshalb das Token. 
Gehe auf Version 3.1 und du kannst die Passwort vergessen Links im Template einbauen.

Mit $this->recoverPasswordLink bekommst du im Login Template "be_login.html5" die url und mit $this->forgotPassword die Übersetzung.

See: https://github.com/markocupic/backend-password-recovery-bundle#readme

**Comment by xstable** [comment]
Ok, nice to be able to set this link now visible all the time, but it still not solve my problem. 
I wonder why my installation doing a redirect to same login-page with `redirect=` parameter all the time, and only call the right url, if I enter the valid login.
It seems to be, that contao on the first request have no matching route, and show the default-login with the referer-parameter (where I do initially want to go to), and if I logged in, he seems to find the route, and do the redirect??!

BTW: https://contao.obkarriere.de/contao/login don't redirect with params, but https://contao.obkarriere.de/contao does!

**Comment by markocupic** [comment]
Hm... I can not reconstruct your issue. I just tested the plugin under a brand new contao 4.9 & 4.11 installation.

**Comment by markocupic** [comment]
Something goes wrong with the routing. 
You could try to debug the routes: `vendor/bin/contao-console debug:router`

https://symfony.com/doc/4.1/routing/debug.html

![image](https://user-images.githubusercontent.com/1525166/120770931-f67cd900-c51e-11eb-802e-c6410f193648.png)

**Comment by markocupic** [comment]
@xstable 
Did you solve your redirecting issue?

**Comment by xstable** [comment]
Not yet, I got this, if I execute your command: 
```
vendor/bin/contao-console debug:router
Content-type: text/html

<br />
<b>Parse error</b>:  syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in <b>/homepages/11/xxxx/htdocs/contao/vendor/contao/manager-bundle/bin/contao-console</b> on line <b>14</b><br />
```

**Comment by markocupic** [comment]
Where did you type this statement? You have to use the console.

**Comment by xstable** [comment]
Yep, looged in via ssh.

Strange, on CLI php-v result in 4.4.9, which might the cause of the issue.
But in the provider-backend ( IONOS ) I see php 7.4.

Ahh, got it, can call php7.4-cli with a prefix: 
![image](https://user-images.githubusercontent.com/1778068/121153129-17f30300-c846-11eb-8060-bae25da648bf.png)

And if I use php7.4 (without -cli): 
![image](https://user-images.githubusercontent.com/1778068/121153753-a10a3a00-c846-11eb-8ecb-d2f9d30dc771.png)

**Comment by markocupic** [comment]
This is strange!

**Comment by markocupic** [comment]
You are using a Contao Managed Edition?
Contao Version 4.9.x ?

**Comment by markocupic** [comment]
What do you get, when you run 

`php vendor/bin/contao-console contao:user:password --help`

[Contao Documentation](https://docs.contao.org/dev/reference/commands)

**Comment by xstable** [comment]
4.9.13 (didn't know here to see which edition this is)

![image](https://user-images.githubusercontent.com/1778068/121154725-7e2c5580-c847-11eb-9e6f-a7d17cc0abc3.png)

**Comment by markocupic** [comment]
If this command is executed correctly, it looks like something is wrong with the routing.

**Comment by markocupic** [comment]
Perhaps your contao installation ist damaged???

**Comment by xstable** [comment]
Don't see any signs for that. The password-remember plugin is the first topic which not work and act a bit strange

**Comment by markocupic** [comment]
You could try to install a dry contao 4.11 with [markocupic/backend-password-recovery-bundle](https://github.com/markocupic/backend-password-recovery-bundle)

**Comment by xstable** [comment]
Ok, it seems that I have to use the CLI-PHP-Version, like described here: 
https://community.contao.org/de/showthread.php?79639-Fehler-beim-Installieren-von-Erweiterungen

But than I got the above error: 
https://user-images.githubusercontent.com/1778068/121153129-17f30300-c846-11eb-8060-bae25da648bf.png
