### ISSUE TITLE
Using recovery link causes 500 error and the backend can be accessed without entering user/password then

### ISSUE THREAD

**Issue by Baloobear** [markocupic/backend-password-recovery-bundle#5]
Hi,

I just installed your plugin on the current Contao version (4.11.5) and found a big issue.

When I clicked on the provided link in the password reset email I face the following issue

> Argument 1 passed to Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher::dispatch() must be an object, string given, called in /usr/src/app/vendor/markocupic/backend-password-recovery-bundle/src/InteractiveLogin/InteractiveBackendLogin.php on line 113

The whole stacktrace

```
TypeError:
Argument 1 passed to Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher::dispatch() must be an object, string given, called in /usr/src/app/vendor/markocupic/backend-password-recovery-bundle/src/InteractiveLogin/InteractiveBackendLogin.php on line 113

  at vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:131
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('security.interactive_login', object(InteractiveLoginEvent))
     (vendor/markocupic/backend-password-recovery-bundle/src/InteractiveLogin/InteractiveBackendLogin.php:113)
  at Markocupic\BackendPasswordRecoveryBundle\InteractiveLogin\InteractiveBackendLogin->login('<STRIPPED_USERNAME>')
     (vendor/markocupic/backend-password-recovery-bundle/src/Controller/RenewPasswordController.php:114)
  at Markocupic\BackendPasswordRecoveryBundle\Controller\RenewPasswordController->renewpasswordAction('622f53124ca3e8b684928a801bdbbac3')
     (vendor/symfony/http-kernel/HttpKernel.php:157)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:79)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:195)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/index.php:31)
```

When I then try to access the Contao backend again I'm automatically logged as that user the password reset was requested for in instead of getting to the form for setting a new password.

I assume this is not a wanted behavior.

I'm running on a PHP 7.4.19 environment.

If you need any further information please let me know.

Thanks,
Dennis

**Comment by markocupic** [comment]
Hi Dennis
No, this is of course not a wanted behaviour. Actually I can not reproduce the error. But we should fix this issue as soon as possible.
Could you send me your composer.json?
Regards 
Marko

**Comment by markocupic** [comment]
Hi Dennis

I found out that the error only occurs if you run contao under symfony > 5.0. 
In Symfony 5 the function argument order for event dispatchers has switched. The event object has to be passed as the first argument to the event dispatcher method. And the second argument (the event name) is optional now.

Symfony 5:
https://github.com/symfony/event-dispatcher/blob/3dcbd3c8e4290c4e7ce362c91d9db5f52fe0b2a7/Debug/TraceableEventDispatcher.php#L131

Symfony 4:
https://github.com/symfony/event-dispatcher/blob/f5741bb072896d8cbf102f7f724cff2b45a6e710/Debug/TraceableEventDispatcher.php#L136

Please update markocupic/backend-password-recovery-bundle to the current version or at least [1.3.19](https://github.com/markocupic/backend-password-recovery-bundle/tree/1.3.19)

Regards 

Marko

**Comment by Baloobear** [comment]
Hello Marko,

thanks for your quick response and also the quick fix. It worked so far. 👍

I also took a quick look in the source code but had no time to create a PR.

But one question kept left for me: is the usage of the variable `$providerKey` in the `InteractiveBackendLogin.php` (Line 108) an old code fragment? Because this variable is not defined anywhere (but I'm not too deep into the Contao plugin development to be honest).

Kind Regards,
Dennis
