### ISSUE TITLE
Feature request: no recovery option if backend user is disabled

### ISSUE THREAD

**Issue by Baloobear** [markocupic/backend-password-recovery-bundle#6]
Hi Marko,

is there a chance to prevent the password recovery button if a disabled or not available user tries to login? I think it is no valid feature to provide a password recovery option in these cases.

Kind regards,
Dennis

**Comment by markocupic** [comment]
Hi Dennis
I implemented your idea in da0cc36.
You should update to 1.3.20.
Kind regards
Marko
